### ISSUE TITLE
I need Cross Shard Assonciation - NHibernate.Shards.CrossShardAssociationException, 

### ISSUE THREAD

**Issue by mesutcakir** [darioquintana/NHibernate-Shards#2] opened 2019-03-01 09:07 UTC
My works in a problem. https://github.com/mesutcakir/NHibernate-Shards?organization=mesutcakir&organization=mesutcakir

![image](https://user-images.githubusercontent.com/4125460/53627092-90ef6300-3c18-11e9-8998-570307e7deaa.png)

![image](https://user-images.githubusercontent.com/4125460/53626957-2a6a4500-3c18-11e9-9dd1-dbf39b8c19ff.png)

```
`İşlenmeyen Özel Durum: NHibernate.Shards.CrossShardAssociationException: Object of entity type 'NHibernate.Shards.Demo.Task' is on shard '0' but an associated object of type 'NHibernate.Shards.Demo.Project' is on shard '1'.
   konum: NHibernate.Shards.Session.ShardedSessionImpl.ThrowIfConflictingShardId(String entityName, ShardId shardId, KeyValuePair2 associatedShardId)
   konum: NHibernate.Shards.Session.ShardedSessionImpl.TryGetShardIdOfAssociatedObject(String entityName, Object entity, ShardId& result)
   konum: NHibernate.Shards.Session.ShardedSessionImpl.SelectShardIdForNewEntity(String entityName, Object entity)
   konum: NHibernate.Shards.Session.ShardedSessionImpl.Save(String entityName, Object obj)
   konum: NHibernate.Shards.Session.ShardedSessionImpl.Save(Object obj)
   konum: NHibernate.Shards.Demo.FirmBasedApp.CreateTask(ISession session, Project project, String name, DayBase dayBase)
   konum: NHibernate.Shards.Demo.FirmBasedApp.AddData()
   konum: NHibernate.Shards.Demo.FirmBasedApp.Run()
   konum: NHibernate.Shards.Demo.FirmBasedApp.Main(String[] args)
Press any key to continue . . .`
```

I search this referances. Virtual Shards - https://docs.jboss.org/hibernate/stable/shards/reference/en/html/shards-resharding.html

But not working. "System.Collections.Generic.KeyNotFoundException"

![image](https://user-images.githubusercontent.com/4125460/53627566-d2ccd900-3c19-11e9-8a07-a4b39c626efb.png)
```
`var virtualShardMap = new Dictionary<short, short>
            {
                { 0, 0 },
                { 1, 0 },
                { 2, 0 },
                { 3, 0 }
            };
            return new ShardedConfiguration(prototypeConfig, shardConfigs, shardStrategyFactory, virtualShardMap);`
```
![image](https://user-images.githubusercontent.com/4125460/53627690-2c350800-3c1a-11e9-98f6-31d27eef74c6.png)

```
İşlenmeyen Özel Durum: System.Collections.Generic.KeyNotFoundException: Verilen anahtar sözlükte yoktu.
   konum: System.ThrowHelper.ThrowKeyNotFoundException()
   konum: System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   konum: NHibernate.Shards.ShardedConfiguration..ctor(Configuration prototypeConfiguration, IEnumerable`1 shardConfigs, IShardStrategyFactory shardStrategyFactory, Dictionary`2 virtualShardToShardMap)
   konum: NHibernate.Shards.Demo.FirmBasedApp.BuildShardedConfiguration()
   konum: NHibernate.Shards.Demo.FirmBasedApp.Run()
   konum: NHibernate.Shards.Demo.FirmBasedApp.Main(String[] args)
Press any key to continue . . .
```
NHibernate.Shards => ShardedConfiguration

![image](https://user-images.githubusercontent.com/4125460/53628007-f3e1f980-3c1a-11e9-8c00-736b8fb7a040.png)
```

if (virtualShardToShardMap.Count != 0)
{
    // build the map from shard to set of virtual shards
    shardToVirtualShardIdMap = new Dictionary<short, ICollection<ShardId>>();
    foreach (var pair in virtualShardToShardMap)
    {
        var set = shardToVirtualShardIdMap[(pair.Value)]; //**Problem Here.**
        // see if we already have a set of virtual shards
        if (set == null)
        {
             // we don't, so create it and add it to the map
             set = new HashSet<ShardId>();
             shardToVirtualShardIdMap.Add(pair.Value, set);
        }
        set.Add(new ShardId(pair.Key));
        }
    }
```

**Comment by ggeurts** [comment] 2019-03-04 14:16
I am afraid cross-shard associations are not supported by design. Virtual shards support storing data of multiple virtual shards in one physical shard, but does not enable cross-referencing between shards.

**Comment by ggeurts** [comment] 2019-04-25 14:41
Closing because behavior is by design

**Closed by ggeurts** 2019-04-25 14:41 UTC
